# Docker compose makes it easier to run our container
version: "3.7"
services:
  e3-app:
    container_name: e3-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-services
    restart: unless-stopped
    ports:
      - 80:80 # We can accept HTTP requests on port 80 and redirect to HTTPS
      - 443:443 #HTTPS
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile # Mount our Caddyfile
      - $PWD/site:/services # Mount our site folder
      - caddy_data:/data # Mount our data folder
      - caddy_config:/config # Mount our config folder
volumes:
  caddy_data:
  caddy_config:
